// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/airplane.proto
// Protobuf Java Version: 4.26.1

package com.nyrta1.SkyTicket_AdminService.models;

public final class AirplaneEntity {
  private AirplaneEntity() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      AirplaneEntity.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AirplaneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Airplane)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int32 manufacturer_id = 2;</code>
     * @return The manufacturerId.
     */
    int getManufacturerId();

    /**
     * <code>int32 manufacturer_year = 3;</code>
     * @return The manufacturerYear.
     */
    int getManufacturerYear();

    /**
     * <code>int32 first_slot_capacity = 4;</code>
     * @return The firstSlotCapacity.
     */
    int getFirstSlotCapacity();

    /**
     * <code>int32 economy_slot_capacity = 5;</code>
     * @return The economySlotCapacity.
     */
    int getEconomySlotCapacity();

    /**
     * <code>int32 country_origin_id = 6;</code>
     * @return The countryOriginId.
     */
    int getCountryOriginId();

    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return The updatedAt.
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code Airplane}
   */
  public static final class Airplane extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Airplane)
      AirplaneOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Airplane.class.getName());
    }
    // Use Airplane.newBuilder() to construct.
    private Airplane(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Airplane() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.class, com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int MANUFACTURER_ID_FIELD_NUMBER = 2;
    private int manufacturerId_ = 0;
    /**
     * <code>int32 manufacturer_id = 2;</code>
     * @return The manufacturerId.
     */
    @java.lang.Override
    public int getManufacturerId() {
      return manufacturerId_;
    }

    public static final int MANUFACTURER_YEAR_FIELD_NUMBER = 3;
    private int manufacturerYear_ = 0;
    /**
     * <code>int32 manufacturer_year = 3;</code>
     * @return The manufacturerYear.
     */
    @java.lang.Override
    public int getManufacturerYear() {
      return manufacturerYear_;
    }

    public static final int FIRST_SLOT_CAPACITY_FIELD_NUMBER = 4;
    private int firstSlotCapacity_ = 0;
    /**
     * <code>int32 first_slot_capacity = 4;</code>
     * @return The firstSlotCapacity.
     */
    @java.lang.Override
    public int getFirstSlotCapacity() {
      return firstSlotCapacity_;
    }

    public static final int ECONOMY_SLOT_CAPACITY_FIELD_NUMBER = 5;
    private int economySlotCapacity_ = 0;
    /**
     * <code>int32 economy_slot_capacity = 5;</code>
     * @return The economySlotCapacity.
     */
    @java.lang.Override
    public int getEconomySlotCapacity() {
      return economySlotCapacity_;
    }

    public static final int COUNTRY_ORIGIN_ID_FIELD_NUMBER = 6;
    private int countryOriginId_ = 0;
    /**
     * <code>int32 country_origin_id = 6;</code>
     * @return The countryOriginId.
     */
    @java.lang.Override
    public int getCountryOriginId() {
      return countryOriginId_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return Whether the updatedAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (manufacturerId_ != 0) {
        output.writeInt32(2, manufacturerId_);
      }
      if (manufacturerYear_ != 0) {
        output.writeInt32(3, manufacturerYear_);
      }
      if (firstSlotCapacity_ != 0) {
        output.writeInt32(4, firstSlotCapacity_);
      }
      if (economySlotCapacity_ != 0) {
        output.writeInt32(5, economySlotCapacity_);
      }
      if (countryOriginId_ != 0) {
        output.writeInt32(6, countryOriginId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(7, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(8, getUpdatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (manufacturerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, manufacturerId_);
      }
      if (manufacturerYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, manufacturerYear_);
      }
      if (firstSlotCapacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, firstSlotCapacity_);
      }
      if (economySlotCapacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, economySlotCapacity_);
      }
      if (countryOriginId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, countryOriginId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getUpdatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane)) {
        return super.equals(obj);
      }
      com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane other = (com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane) obj;

      if (getId()
          != other.getId()) return false;
      if (getManufacturerId()
          != other.getManufacturerId()) return false;
      if (getManufacturerYear()
          != other.getManufacturerYear()) return false;
      if (getFirstSlotCapacity()
          != other.getFirstSlotCapacity()) return false;
      if (getEconomySlotCapacity()
          != other.getEconomySlotCapacity()) return false;
      if (getCountryOriginId()
          != other.getCountryOriginId()) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MANUFACTURER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerId();
      hash = (37 * hash) + MANUFACTURER_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerYear();
      hash = (37 * hash) + FIRST_SLOT_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getFirstSlotCapacity();
      hash = (37 * hash) + ECONOMY_SLOT_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getEconomySlotCapacity();
      hash = (37 * hash) + COUNTRY_ORIGIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCountryOriginId();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Airplane}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Airplane)
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.AirplaneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.class, com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.Builder.class);
      }

      // Construct using com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getCreatedAtFieldBuilder();
          getUpdatedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        manufacturerId_ = 0;
        manufacturerYear_ = 0;
        firstSlotCapacity_ = 0;
        economySlotCapacity_ = 0;
        countryOriginId_ = 0;
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstanceForType() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.getDefaultInstance();
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane build() {
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane buildPartial() {
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result = new com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.manufacturerId_ = manufacturerId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.manufacturerYear_ = manufacturerYear_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.firstSlotCapacity_ = firstSlotCapacity_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.economySlotCapacity_ = economySlotCapacity_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.countryOriginId_ = countryOriginId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.updatedAt_ = updatedAtBuilder_ == null
              ? updatedAt_
              : updatedAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane) {
          return mergeFrom((com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane other) {
        if (other == com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getManufacturerId() != 0) {
          setManufacturerId(other.getManufacturerId());
        }
        if (other.getManufacturerYear() != 0) {
          setManufacturerYear(other.getManufacturerYear());
        }
        if (other.getFirstSlotCapacity() != 0) {
          setFirstSlotCapacity(other.getFirstSlotCapacity());
        }
        if (other.getEconomySlotCapacity() != 0) {
          setEconomySlotCapacity(other.getEconomySlotCapacity());
        }
        if (other.getCountryOriginId() != 0) {
          setCountryOriginId(other.getCountryOriginId());
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                manufacturerId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                manufacturerYear_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                firstSlotCapacity_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                economySlotCapacity_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                countryOriginId_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                input.readMessage(
                    getUpdatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int manufacturerId_ ;
      /**
       * <code>int32 manufacturer_id = 2;</code>
       * @return The manufacturerId.
       */
      @java.lang.Override
      public int getManufacturerId() {
        return manufacturerId_;
      }
      /**
       * <code>int32 manufacturer_id = 2;</code>
       * @param value The manufacturerId to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerId(int value) {

        manufacturerId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 manufacturer_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        manufacturerId_ = 0;
        onChanged();
        return this;
      }

      private int manufacturerYear_ ;
      /**
       * <code>int32 manufacturer_year = 3;</code>
       * @return The manufacturerYear.
       */
      @java.lang.Override
      public int getManufacturerYear() {
        return manufacturerYear_;
      }
      /**
       * <code>int32 manufacturer_year = 3;</code>
       * @param value The manufacturerYear to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerYear(int value) {

        manufacturerYear_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 manufacturer_year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturerYear() {
        bitField0_ = (bitField0_ & ~0x00000004);
        manufacturerYear_ = 0;
        onChanged();
        return this;
      }

      private int firstSlotCapacity_ ;
      /**
       * <code>int32 first_slot_capacity = 4;</code>
       * @return The firstSlotCapacity.
       */
      @java.lang.Override
      public int getFirstSlotCapacity() {
        return firstSlotCapacity_;
      }
      /**
       * <code>int32 first_slot_capacity = 4;</code>
       * @param value The firstSlotCapacity to set.
       * @return This builder for chaining.
       */
      public Builder setFirstSlotCapacity(int value) {

        firstSlotCapacity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 first_slot_capacity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstSlotCapacity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        firstSlotCapacity_ = 0;
        onChanged();
        return this;
      }

      private int economySlotCapacity_ ;
      /**
       * <code>int32 economy_slot_capacity = 5;</code>
       * @return The economySlotCapacity.
       */
      @java.lang.Override
      public int getEconomySlotCapacity() {
        return economySlotCapacity_;
      }
      /**
       * <code>int32 economy_slot_capacity = 5;</code>
       * @param value The economySlotCapacity to set.
       * @return This builder for chaining.
       */
      public Builder setEconomySlotCapacity(int value) {

        economySlotCapacity_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 economy_slot_capacity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEconomySlotCapacity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        economySlotCapacity_ = 0;
        onChanged();
        return this;
      }

      private int countryOriginId_ ;
      /**
       * <code>int32 country_origin_id = 6;</code>
       * @return The countryOriginId.
       */
      @java.lang.Override
      public int getCountryOriginId() {
        return countryOriginId_;
      }
      /**
       * <code>int32 country_origin_id = 6;</code>
       * @param value The countryOriginId to set.
       * @return This builder for chaining.
       */
      public Builder setCountryOriginId(int value) {

        countryOriginId_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 country_origin_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryOriginId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        countryOriginId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.google.protobuf.Timestamp updatedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       * @return The updatedAt.
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
        } else {
          updatedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
            updatedAt_ != null &&
            updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getUpdatedAtBuilder().mergeFrom(value);
          } else {
            updatedAt_ = value;
          }
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }
        if (updatedAt_ != null) {
          bitField0_ |= 0x00000080;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000080);
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Airplane)
    }

    // @@protoc_insertion_point(class_scope:Airplane)
    private static final com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane();
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Airplane>
        PARSER = new com.google.protobuf.AbstractParser<Airplane>() {
      @java.lang.Override
      public Airplane parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Airplane> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Airplane> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Airplane_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Airplane_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/airplane.proto\032\037google/protobuf/" +
      "timestamp.proto\"\201\002\n\010Airplane\022\n\n\002id\030\001 \001(\003" +
      "\022\027\n\017manufacturer_id\030\002 \001(\005\022\031\n\021manufacture" +
      "r_year\030\003 \001(\005\022\033\n\023first_slot_capacity\030\004 \001(" +
      "\005\022\035\n\025economy_slot_capacity\030\005 \001(\005\022\031\n\021coun" +
      "try_origin_id\030\006 \001(\005\022.\n\ncreated_at\030\007 \001(\0132" +
      "\032.google.protobuf.Timestamp\022.\n\nupdated_a" +
      "t\030\010 \001(\0132\032.google.protobuf.TimestampB:\n(c" +
      "om.nyrta1.SkyTicket_AdminService.modelsB" +
      "\016AirplaneEntityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Airplane_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Airplane_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Airplane_descriptor,
        new java.lang.String[] { "Id", "ManufacturerId", "ManufacturerYear", "FirstSlotCapacity", "EconomySlotCapacity", "CountryOriginId", "CreatedAt", "UpdatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
