// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/airplane.proto
// Protobuf Java Version: 4.26.1

package com.nyrta1.SkyTicket_AdminService.models;

public final class AirplaneEntity {
  private AirplaneEntity() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      AirplaneEntity.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AirplaneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Airplane)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>string manufacturer = 3;</code>
     * @return The manufacturer.
     */
    java.lang.String getManufacturer();
    /**
     * <code>string manufacturer = 3;</code>
     * @return The bytes for manufacturer.
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>int32 capacity = 4;</code>
     * @return The capacity.
     */
    int getCapacity();

    /**
     * <code>string registrationNumber = 5;</code>
     * @return The registrationNumber.
     */
    java.lang.String getRegistrationNumber();
    /**
     * <code>string registrationNumber = 5;</code>
     * @return The bytes for registrationNumber.
     */
    com.google.protobuf.ByteString
        getRegistrationNumberBytes();
  }
  /**
   * Protobuf type {@code Airplane}
   */
  public static final class Airplane extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Airplane)
      AirplaneOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Airplane.class.getName());
    }
    // Use Airplane.newBuilder() to construct.
    private Airplane(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Airplane() {
      model_ = "";
      manufacturer_ = "";
      registrationNumber_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.class, com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int MODEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object model_ = "";
    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object manufacturer_ = "";
    /**
     * <code>string manufacturer = 3;</code>
     * @return The manufacturer.
     */
    @java.lang.Override
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      }
    }
    /**
     * <code>string manufacturer = 3;</code>
     * @return The bytes for manufacturer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPACITY_FIELD_NUMBER = 4;
    private int capacity_ = 0;
    /**
     * <code>int32 capacity = 4;</code>
     * @return The capacity.
     */
    @java.lang.Override
    public int getCapacity() {
      return capacity_;
    }

    public static final int REGISTRATIONNUMBER_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object registrationNumber_ = "";
    /**
     * <code>string registrationNumber = 5;</code>
     * @return The registrationNumber.
     */
    @java.lang.Override
    public java.lang.String getRegistrationNumber() {
      java.lang.Object ref = registrationNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registrationNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string registrationNumber = 5;</code>
     * @return The bytes for registrationNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegistrationNumberBytes() {
      java.lang.Object ref = registrationNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registrationNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, model_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(manufacturer_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, manufacturer_);
      }
      if (capacity_ != 0) {
        output.writeInt32(4, capacity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(registrationNumber_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, registrationNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, model_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(manufacturer_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, manufacturer_);
      }
      if (capacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, capacity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(registrationNumber_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, registrationNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane)) {
        return super.equals(obj);
      }
      com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane other = (com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane) obj;

      if (getId()
          != other.getId()) return false;
      if (!getModel()
          .equals(other.getModel())) return false;
      if (!getManufacturer()
          .equals(other.getManufacturer())) return false;
      if (getCapacity()
          != other.getCapacity()) return false;
      if (!getRegistrationNumber()
          .equals(other.getRegistrationNumber())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturer().hashCode();
      hash = (37 * hash) + CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getCapacity();
      hash = (37 * hash) + REGISTRATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationNumber().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Airplane}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Airplane)
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.AirplaneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.class, com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.Builder.class);
      }

      // Construct using com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        model_ = "";
        manufacturer_ = "";
        capacity_ = 0;
        registrationNumber_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.internal_static_Airplane_descriptor;
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstanceForType() {
        return com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.getDefaultInstance();
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane build() {
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane buildPartial() {
        com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result = new com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.model_ = model_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.manufacturer_ = manufacturer_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.capacity_ = capacity_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.registrationNumber_ = registrationNumber_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane) {
          return mergeFrom((com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane other) {
        if (other == com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getManufacturer().isEmpty()) {
          manufacturer_ = other.manufacturer_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getCapacity() != 0) {
          setCapacity(other.getCapacity());
        }
        if (!other.getRegistrationNumber().isEmpty()) {
          registrationNumber_ = other.registrationNumber_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                model_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                manufacturer_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                capacity_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                registrationNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 2;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 2;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 2;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        model_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        model_ = getDefaultInstance().getModel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string model = 2;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        model_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object manufacturer_ = "";
      /**
       * <code>string manufacturer = 3;</code>
       * @return The manufacturer.
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manufacturer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string manufacturer = 3;</code>
       * @return The bytes for manufacturer.
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string manufacturer = 3;</code>
       * @param value The manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        manufacturer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturer() {
        manufacturer_ = getDefaultInstance().getManufacturer();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 3;</code>
       * @param value The bytes for manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        manufacturer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int capacity_ ;
      /**
       * <code>int32 capacity = 4;</code>
       * @return The capacity.
       */
      @java.lang.Override
      public int getCapacity() {
        return capacity_;
      }
      /**
       * <code>int32 capacity = 4;</code>
       * @param value The capacity to set.
       * @return This builder for chaining.
       */
      public Builder setCapacity(int value) {

        capacity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 capacity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCapacity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        capacity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object registrationNumber_ = "";
      /**
       * <code>string registrationNumber = 5;</code>
       * @return The registrationNumber.
       */
      public java.lang.String getRegistrationNumber() {
        java.lang.Object ref = registrationNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          registrationNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string registrationNumber = 5;</code>
       * @return The bytes for registrationNumber.
       */
      public com.google.protobuf.ByteString
          getRegistrationNumberBytes() {
        java.lang.Object ref = registrationNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registrationNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string registrationNumber = 5;</code>
       * @param value The registrationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        registrationNumber_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string registrationNumber = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegistrationNumber() {
        registrationNumber_ = getDefaultInstance().getRegistrationNumber();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string registrationNumber = 5;</code>
       * @param value The bytes for registrationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        registrationNumber_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Airplane)
    }

    // @@protoc_insertion_point(class_scope:Airplane)
    private static final com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane();
    }

    public static com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Airplane>
        PARSER = new com.google.protobuf.AbstractParser<Airplane>() {
      @java.lang.Override
      public Airplane parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Airplane> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Airplane> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nyrta1.SkyTicket_AdminService.models.AirplaneEntity.Airplane getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Airplane_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Airplane_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036resources/proto/airplane.proto\"i\n\010Airp" +
      "lane\022\n\n\002id\030\001 \001(\003\022\r\n\005model\030\002 \001(\t\022\024\n\014manuf" +
      "acturer\030\003 \001(\t\022\020\n\010capacity\030\004 \001(\005\022\032\n\022regis" +
      "trationNumber\030\005 \001(\tB:\n(com.nyrta1.SkyTic" +
      "ket_AdminService.modelsB\016AirplaneEntityb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Airplane_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Airplane_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Airplane_descriptor,
        new java.lang.String[] { "Id", "Model", "Manufacturer", "Capacity", "RegistrationNumber", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
